'use client';

import { useState } from 'react';
import Button from '@/components/ui/Button';

export default function ExportPage() {
  const [exporting, setExporting] = useState(false);
  const [bookContent, setBookContent] = useState('');

  // Quick function to format book as Markdown
  const formatBookAsMarkdown = (book: any) => {
    let markdown = `# ${book.title}\n\n## ${book.subtitle}\n\n---\n\n`;
    
    book.chapters.forEach((chapter: any, index: number) => {
      markdown += `## Chapter ${index + 1}: ${chapter.title}\n\n`;
      markdown += chapter.content + '\n\n---\n\n';
    });
    
    markdown += `\n\n## About This Book\n\nThis satirical self-help book was generated by BScribe.ai, an AI that's refreshingly honest about being full of sh*t.\n\n`;
    markdown += `Unlike other self-help books, we admit upfront that this is algorithmically generated nonsense designed to make you laugh at the absurdity of the self-help industry.\n\n`;
    markdown += `© 2024 BScribe.ai - Because someone had to say it.`;
    
    return markdown;
  };

  const handleExportBook = async (bookId: string) => {
    setExporting(true);
    
    // Fetch book from your database
    const response = await fetch(`/api/admin/books/${bookId}`);
    const book = await response.json();
    
    // Format as markdown
    const markdown = formatBookAsMarkdown(book);
    setBookContent(markdown);
    
    // For now, display it so you can copy-paste
    // Later we'll add PDF generation
    setExporting(false);
  };

  return (
    <div className="container mx-auto p-8 text-white">
      <h1 className="text-3xl font-bold mb-8">Export Books to PDF</h1>
      
      <div className="mb-8">
        <h2 className="text-xl mb-4">Quick Export Instructions:</h2>
        <ol className="list-decimal pl-6 space-y-2 text-gray-300">
          <li>Generate a book using the main admin interface</li>
          <li>Click "Export" below to get the Markdown</li>
          <li>Copy the markdown content</li>
          <li>Go to <a href="https://www.markdowntopdf.com/" target="_blank" className="text-emerald-500 underline">markdowntopdf.com</a></li>
          <li>Paste and download as PDF</li>
          <li>Upload to Supabase Storage</li>
        </ol>
      </div>

      <div className="space-y-4">
        <Button onClick={() => handleExportBook('your-book-id')} loading={exporting}>
          Export Book 1
        </Button>
        
        {bookContent && (
          <div className="mt-8">
            <h3 className="text-lg font-bold mb-2">Markdown Content (Copy This):</h3>
            <textarea 
              value={bookContent}
              readOnly
              className="w-full h-96 p-4 bg-gray-900 text-gray-100 rounded font-mono text-sm"
              onClick={(e) => e.currentTarget.select()}
            />
          </div>
        )}
      </div>
    </div>
  );
}