// Replace your /app/layout.tsx with this updated version

import { Metadata } from 'next';
import Footer from '@/components/ui/Footer';
import Navbar from '@/components/ui/Navbar';
import { Toaster } from '@/components/ui/Toasts/toaster';
import { PropsWithChildren, Suspense } from 'react';
import { getURL } from '@/utils/helpers';
import { SpeedInsights } from "@vercel/speed-insights/next"
import 'styles/main.css';

const title = 'Bscribe - Self-Help Books That Admit They\'re Full of Sh*t';
const description = 'Satirical self-help books generated by AI. Finally, honest advice that admits it doesn\'t know what it\'s talking about. Buy our bullsh*t instead of making your own.';

export const metadata: Metadata = {
  metadataBase: new URL(getURL()),
  title: title,
  description: description,
  openGraph: {
    title: title,
    description: description,
    type: 'website',
    url: getURL(),
  },
  twitter: {
    card: 'summary_large_image',
    title: title,
    description: description,
  },
  keywords: [
    'satirical self-help',
    'funny self-help books', 
    'AI generated books',
    'parody self-improvement',
    'comedy ebooks',
    'fake self-help'
  ]
};

export default async function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body className="bg-black">
        <Navbar />
        <main
          id="skip"
          className="min-h-[calc(100dvh-4rem)] md:min-h[calc(100dvh-5rem)]"
        >
          {children}
          <SpeedInsights />
        </main>
        <Footer />
        <Suspense>
          <Toaster />
        </Suspense>
      </body>
    </html>
  );
}