'use client';

import { useState } from 'react';
import Button from '@/components/ui/Button';
import { getStripe } from '@/utils/stripe/client';

// Book data with prices in cents
const featuredBooks = [
  {
    id: 1,
    title: "The 7 F*cking Secrets of How to Hack the Art of Everything You Need to Know",
    price: 9.99,
    priceInCents: 999,
    description: "Finally, a self-help book that admits it's completely made up.",
    coverUrl: "/placeholder-cover-1.jpg"
  },
  {
    id: 2,
    title: "Think Like a Motherf*cking Navy SEAL CEO", 
    price: 12.99,
    priceInCents: 1299,
    description: "Corporate buzzwords meet military discipline meets absolute nonsense.",
    coverUrl: "/placeholder-cover-2.jpg"
  },
  {
    id: 3,
    title: "From Broke-Ass Loser to F*ckable Billionaire in 30 Minutes",
    price: 7.99,
    priceInCents: 799,
    description: "The quickest path to success that definitely won't work.",
    coverUrl: "/placeholder-cover-3.jpg"
  },
  {
    id: 4,
    title: "The 42-Parameter Deep Learning Framework for Optimizing Your Neural Pathways",
    price: 14.99,
    priceInCents: 1499,
    description: "AI-speak meets self-help. It's as confused as you are.",
    coverUrl: "/placeholder-cover-4.jpg"
  },
  {
    id: 5,
    title: "Authentically Leveraging Your Personal Brand's F*cking Synergy",
    price: 11.99,
    priceInCents: 1199,
    description: "LinkedIn thought leadership at its most ridiculous.",
    coverUrl: "/placeholder-cover-5.jpg"
  },
  {
    id: 6,
    title: "Zero-Shot Learning the Art of Maximum F*ckery",
    price: 8.99,
    priceInCents: 899,
    description: "Machine learning meets life advice. Neither makes sense.",
    coverUrl: "/placeholder-cover-6.jpg"
  }
];

export default function HomePage() {
  const [loading, setLoading] = useState<number | null>(null);

  const handleBuyBook = async (book: any) => {
    setLoading(book.id);
    
    try {
      // Create checkout session
      const response = await fetch('/api/create-checkout', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          priceId: book.priceInCents,
          bookTitle: book.title,
        }),
      });

      const { sessionId } = await response.json();

      // Redirect to Stripe Checkout
      const stripe = await getStripe();
      await stripe?.redirectToCheckout({ sessionId });
    } catch (error) {
      console.error('Error:', error);
      alert('Something went wrong. Please try again.');
    } finally {
      setLoading(null);
    }
  };

  const handleBuyBundle = async () => {
    setLoading(999);
    
    try {
      const response = await fetch('/api/create-checkout', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          priceId: 3999, // $39.99 in cents
          bookTitle: 'Complete Bullsh*t Bundle - All 6 Books',
        }),
      });

      const { sessionId } = await response.json();
      const stripe = await getStripe();
      await stripe?.redirectToCheckout({ sessionId });
    } catch (error) {
      console.error('Error:', error);
      alert('Something went wrong. Please try again.');
    } finally {
      setLoading(null);
    }
  };

  return (
    <div className="bg-black text-white">
      {/* Hero Section */}
      <section className="min-h-screen flex items-center justify-center px-4 py-20">
        <div className="max-w-6xl mx-auto text-center">
          {/* Main Headline */}
          <h1 className="text-6xl md:text-8xl font-black mb-6 leading-tight">
            I Wasted{' '}
            <span className="text-yellow-400">6 Months</span>
            <br />
            Building This So{' '}
            <span className="text-yellow-400">You Don't Have To</span>
          </h1>
          
          {/* Subheadline */}
          <p className="text-xl md:text-2xl mb-12 text-gray-300 max-w-4xl mx-auto">
            Satirical self-help books generated by AI. Yes, it's as stupid as it sounds. 
            No, I'm not sorry. My therapist says this is "concerning behavior," 
            but my Stripe dashboard says otherwise.
          </p>

          {/* Featured Books Grid */}
          <div id="books" className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mb-12">
            {featuredBooks.map((book) => (
              <div
                key={book.id}
                className="bg-gray-900 rounded-lg p-6 hover:bg-gray-800 transition-all duration-300 hover:scale-105"
              >
                {/* Placeholder for book cover image */}
                <div className="bg-gray-200 h-48 rounded-lg mb-4 flex items-center justify-center">
                  <span className="text-gray-500 text-sm">Book Cover Image</span>
                </div>
                
                <h3 className="font-bold text-lg mb-2 line-clamp-2 min-h-[3.5rem]">
                  {book.title}
                </h3>
                
                <p className="text-gray-400 text-sm mb-4">
                  {book.description}
                </p>
                
                <div className="text-center">
                  <div className="text-yellow-400 font-bold text-xl mb-3">
                    ${book.price}
                  </div>
                  <Button
                    variant="slim"
                    className="bg-red-600 hover:bg-red-700 text-white px-6 py-2 disabled:opacity-50 w-full"
                    onClick={() => handleBuyBook(book)}
                    disabled={loading === book.id}
                  >
                    {loading === book.id ? 'Loading...' : 'Buy This Bullsh*t'}
                  </Button>
                </div>
              </div>
            ))}
          </div>

          {/* Main CTA */}
          <div id="bundle">
            <Button
            variant="slim"
            className="bg-yellow-400 hover:bg-yellow-500 text-black font-bold text-xl px-12 py-4 rounded-lg shadow-lg transform hover:scale-105 transition-all disabled:opacity-50"
            onClick={handleBuyBundle}
            disabled={loading === 999}
          >
            {loading === 999 ? 'Loading...' : 'Get All 6 Books for $39.99 (Save Your Dignity Later)'}
          </Button>
        </div>
        </div>
      </section>

      {/* Problem Section */}
      <section className="py-20 px-4 bg-gray-900">
        <div className="max-w-4xl mx-auto text-center">
          <h2 className="text-4xl md:text-5xl font-bold mb-8">
            Look, Let's Be <span className="text-yellow-400">Honest</span>
          </h2>
          
          <div className="text-lg md:text-xl space-y-6 text-gray-300">
            <p>
              You came here because you saw a ridiculous book title somewhere and thought "haha, that's funny." 
              Now you're actually considering buying it. We both know you could probably write this garbage 
              yourself in 20 minutes, but here we are.
            </p>
            
            <p>
              I spent actual human hours creating a website that sells fake self-help books written by a robot. 
              You could spend your Tuesday evening doing the same thing, or just give me some money 
              and go back to scrolling TikTok like a normal person.
            </p>
            
            <p>
              <strong>The deal:</strong> You give me money, I give you a PDF that will make you laugh for 5 minutes, 
              then you'll forget about it forever. It's like buying a coffee, except the coffee is existential 
              dread with Comic Sans formatting.
            </p>
          </div>
        </div>
      </section>

      {/* Social Proof (Obviously Fake) */}
      <section className="py-20 px-4">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-4xl font-bold text-center mb-12">
            Join <span className="text-yellow-400">420 People</span> Who've Lost Their Dignity
          </h2>
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div className="bg-gray-900 p-6 rounded-lg">
              <p className="text-gray-300 mb-4">
                "I bought this ironically but now I genuinely can't tell if it's helping or making things worse. 10/10."
              </p>
              <p className="text-yellow-400 font-bold">- Sarah K., Professional Overthinker</p>
            </div>
            
            <div className="bg-gray-900 p-6 rounded-lg">
              <p className="text-gray-300 mb-4">
                "Finally, self-help that admits it doesn't know what it's talking about. Refreshingly honest."
              </p>
              <p className="text-yellow-400 font-bold">- Mike D., Failed Entrepreneur #7</p>
            </div>
            
            <div className="bg-gray-900 p-6 rounded-lg">
              <p className="text-gray-300 mb-4">
                "I was expecting garbage and got exactly that. Somehow I feel better about my life choices."
              </p>
              <p className="text-yellow-400 font-bold">- Alex R., Recovering Productivity Addict</p>
            </div>
          </div>
          
          {/* Fake counter */}
          <div className="text-center mt-12">
            <p className="text-gray-400">
              <span className="text-yellow-400 font-bold text-2xl">1,247</span> people have wasted their money so far today
            </p>
          </div>
        </div>
      </section>

      {/* Final CTA */}
      <section className="py-20 px-4" style={{backgroundColor: '#ff0000'}}>
        <div className="max-w-4xl mx-auto text-center">
          <h2 className="text-4xl md:text-5xl font-bold mb-8">
            Stop Overthinking It
          </h2>
          
          <p className="text-xl mb-8 text-gray-200">
            You've read this far, which means you're already committed to making questionable decisions today. 
            Might as well buy some books about it.
          </p>
          
          <Button
            variant="slim"
            className="bg-yellow-400 hover:bg-yellow-500 text-black font-bold text-2xl px-16 py-6 rounded-lg shadow-lg transform hover:scale-105 transition-all disabled:opacity-50"
            onClick={handleBuyBundle}
            disabled={loading === 999}
          >
            {loading === 999 ? 'Loading...' : 'the red URGENCY TO BUY is irresistible'}
          </Button>
          
          <p className="text-sm text-gray-400 mt-4">
            No refunds. We don't want it back.
          </p>
        </div>
      </section>
    </div>
  );
}