// utils/bookExport.ts
import jsPDF from 'jspdf';

export interface BookData {
  title: string;
  subtitle: string;
  chapters: Array<{
    title: string;
    content: string;
  }>;
  buyerEmail?: string;
  transactionId?: string;
}

export function generatePDF(book: BookData): Blob {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const lineHeight = 7;
  let yPosition = margin;

  // Watermark function
  const addWatermark = () => {
    if (book.buyerEmail) {
      doc.setFontSize(10);
      doc.setTextColor(200, 200, 200);
      doc.text(book.buyerEmail, pageWidth / 2, pageHeight - 10, { align: 'center' });
    }
  };

  // Title page
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text(book.title, pageWidth / 2, yPosition + 40, { align: 'center', maxWidth: pageWidth - 2 * margin });
  
  yPosition += 60;
  doc.setFontSize(16);
  doc.setFont('helvetica', 'normal');
  doc.text(book.subtitle, pageWidth / 2, yPosition, { align: 'center', maxWidth: pageWidth - 2 * margin });
  
  // Add watermark to title page
  addWatermark();
  
  // Chapters
  book.chapters.forEach((chapter, index) => {
    doc.addPage();
    yPosition = margin;
    
    // Chapter title
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text(`Chapter ${index + 1}`, margin, yPosition);
    yPosition += lineHeight;
    
    doc.setFontSize(14);
    doc.text(chapter.title, margin, yPosition, { maxWidth: pageWidth - 2 * margin });
    yPosition += lineHeight * 2;
    
    // Chapter content
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    
    const lines = doc.splitTextToSize(chapter.content, pageWidth - 2 * margin);
    
    lines.forEach((line: string) => {
      if (yPosition + lineHeight > pageHeight - margin) {
        doc.addPage();
        yPosition = margin;
        addWatermark();
      }
      doc.text(line, margin, yPosition);
      yPosition += lineHeight;
    });
    
    addWatermark();
  });

  // Add final page with copyright
  doc.addPage();
  yPosition = pageHeight / 2;
  doc.setFontSize(12);
  doc.text('© 2024 BScribe.ai', pageWidth / 2, yPosition, { align: 'center' });
  yPosition += lineHeight;
  doc.text('This book was generated by AI that admits it\'s full of BS.', pageWidth / 2, yPosition, { align: 'center' });
  
  return doc.output('blob');
}

// Shareable excerpt generator
export function generateShareableExcerpt(text: string, title: string): string {
  const maxLength = 280; // Twitter-friendly
  const excerpt = text.substring(0, maxLength - title.length - 10);
  return `"${excerpt}..." - ${title} #BScribeAI`;
}