// app/admin/convert/page.tsx
'use client';

import { useState } from 'react';
import Button from '@/components/ui/Button';

export default function ConvertPage() {
  const [jsonContent, setJsonContent] = useState('');
  const [markdown, setMarkdown] = useState('');

  const convertToMarkdown = () => {
    try {
      const book = JSON.parse(jsonContent);
      
      let md = `# ${book.title}\n\n`;
      md += `## ${book.subtitle}\n\n`;
      md += `---\n\n`;
      
      book.chapters.forEach((chapter: any, index: number) => {
        md += `## Chapter ${index + 1}: ${chapter.title}\n\n`;
        md += chapter.content + '\n\n';
        md += `---\n\n`;
      });
      
      md += `## About This Book\n\n`;
      md += `This satirical self-help book was generated by BScribe.ai, an AI that's refreshingly honest about being full of sh*t.\n\n`;
      md += `Unlike other self-help books, we admit upfront that this is algorithmically generated nonsense designed to make you laugh at the absurdity of the self-help industry.\n\n`;
      md += `© 2024 BScribe.ai - All rights reserved.\n\n`;
      md += `Visit us at https://bscribe.ai`;
      
      setMarkdown(md);
    } catch (error) {
      alert('Invalid JSON format');
    }
  };

  const copyMarkdown = () => {
    navigator.clipboard.writeText(markdown);
    alert('Markdown copied to clipboard!');
  };

  return (
    <div className="container mx-auto p-8 text-white max-w-6xl">
      <h1 className="text-3xl font-bold mb-8">Convert Book JSON to PDF</h1>
      
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        <div>
          <h2 className="text-xl mb-4">Step 1: Paste JSON</h2>
          <textarea
            value={jsonContent}
            onChange={(e) => setJsonContent(e.target.value)}
            placeholder="Paste your book JSON here..."
            className="w-full h-96 p-4 bg-gray-900 text-gray-100 rounded font-mono text-sm"
          />
          <Button onClick={convertToMarkdown} className="mt-4">
            Convert to Markdown
          </Button>
        </div>
        
        <div>
          <h2 className="text-xl mb-4">Step 2: Copy Markdown</h2>
          <textarea
            value={markdown}
            readOnly
            placeholder="Markdown will appear here..."
            className="w-full h-96 p-4 bg-gray-900 text-gray-100 rounded font-mono text-sm"
          />
          <Button onClick={copyMarkdown} className="mt-4" disabled={!markdown}>
            Copy Markdown
          </Button>
        </div>
      </div>
      
      <div className="mt-12 p-6 bg-gray-800 rounded">
        <h2 className="text-xl mb-4">Step 3: Convert to PDF</h2>
        <ol className="list-decimal pl-6 space-y-2">
          <li>Go to <a href="https://www.markdowntopdf.com/" target="_blank" className="text-emerald-500 underline">markdowntopdf.com</a></li>
          <li>Paste the markdown</li>
          <li>Adjust settings:
            <ul className="list-disc pl-6 mt-2">
              <li>Set margins to "Normal"</li>
              <li>Enable "Table of Contents" if desired</li>
              <li>Choose "Letter" or "A4" size</li>
            </ul>
          </li>
          <li>Download the PDF</li>
          <li>Review the PDF for formatting</li>
        </ol>
      </div>
      
      <div className="mt-8 p-6 bg-gray-800 rounded">
        <h2 className="text-xl mb-4">Step 4: Upload to Supabase</h2>
        <ol className="list-decimal pl-6 space-y-2">
          <li>Go to your Supabase dashboard</li>
          <li>Navigate to Storage → books bucket</li>
          <li>Upload to the appropriate folder:
            <ul className="list-disc pl-6 mt-2">
              <li><code>individual/</code> for single books</li>
              <li><code>bundles/</code> for the complete bundle</li>
            </ul>
          </li>
          <li>Name files exactly as mapped in your code:
            <ul className="list-disc pl-6 mt-2 text-sm font-mono">
              <li>book-1-seven-secrets.pdf</li>
              <li>book-2-navy-seal-ceo.pdf</li>
              <li>etc.</li>
            </ul>
          </li>
        </ol>
      </div>
    </div>
  );
}